#-------------------------------------------------------------------------------#
#               Qodana analysis is configured by qodana.yaml file               #
#             https://www.jetbrains.com/help/qodana/qodana-yaml.html            #
#-------------------------------------------------------------------------------#
version: "1.0"
linter: jetbrains/qodana-dotnet:2023.3
include:
  - name: CheckDependencyLicenses
    paths:
      - "Editor"
      - "Editor.GUI.CLI"
      - "Runtime"
      - "Plugins"

#Specify IDE code to run analysis without container (Applied in CI/CD pipeline)
ide: QDNET

#Specify inspection profile for code analysis
profile:
  name: qodana.starter

#Enable inspections
#include:
#  - name: <SomeEnabledInspectionId>

#Disable inspections
exclude:
  - name: All
    paths:
      - "Tools~"
      - "Resources"
      - "*.meta"
      - "*.asmdef"
      - "*.tt"

# 指定Qodana 扫描 solution 文件
dot-net:
  solution: "ALL.sln"

#Execute shell command before Qodana execution (Applied in CI/CD pipeline)
#bootstrap: sh ./prepare-qodana.sh

#Install IDE plugins before Qodana execution (Applied in CI/CD pipeline)
#plugins:
#  - id: <plugin.id> #(plugin id can be found at https://plugins.jetbrains.com)