extern "C" {
#include "../../Packages~/WebGLPlugins/lapi.c"
#include "../../Packages~/WebGLPlugins/lauxlib.c"
#include "../../Packages~/WebGLPlugins/lbaselib.c"
#include "../../Packages~/WebGLPlugins/lbitlib.c"
#include "../../Packages~/WebGLPlugins/lcode.c"
#include "../../Packages~/WebGLPlugins/lcorolib.c"
#include "../../Packages~/WebGLPlugins/lctype.c"
#include "../../Packages~/WebGLPlugins/ldblib.c"
#include "../../Packages~/WebGLPlugins/ldebug.c"
#include "../../Packages~/WebGLPlugins/ldo.c"
#include "../../Packages~/WebGLPlugins/ldump.c"
#include "../../Packages~/WebGLPlugins/lfunc.c"
#include "../../Packages~/WebGLPlugins/lgc.c"
#include "../../Packages~/WebGLPlugins/linit.c"
#include "../../Packages~/WebGLPlugins/liolib.c"
#include "../../Packages~/WebGLPlugins/llex.c"
#include "../../Packages~/WebGLPlugins/lmathlib.c"
#include "../../Packages~/WebGLPlugins/lmem.c"
#include "../../Packages~/WebGLPlugins/loadlib.c"
#include "../../Packages~/WebGLPlugins/lobject.c"
#include "../../Packages~/WebGLPlugins/lopcodes.c"
#include "../../Packages~/WebGLPlugins/loslib.c"
#include "../../Packages~/WebGLPlugins/lparser.c"
#include "../../Packages~/WebGLPlugins/lstate.c"
#include "../../Packages~/WebGLPlugins/lstring.c"
#include "../../Packages~/WebGLPlugins/lstrlib.c"
#include "../../Packages~/WebGLPlugins/ltable.c"
#include "../../Packages~/WebGLPlugins/ltablib.c"
#include "../../Packages~/WebGLPlugins/ltm.c"
#include "../../Packages~/WebGLPlugins/lundump.c"
#include "../../Packages~/WebGLPlugins/lutf8lib.c"
#include "../../Packages~/WebGLPlugins/lvm.c"
#include "../../Packages~/WebGLPlugins/lzio.c"
#include "../../Packages~/WebGLPlugins/i64lib.c"
#include "../../Packages~/WebGLPlugins/perflib.c"
#include "../../Packages~/WebGLPlugins/xlua.c"
}



