//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public class DelegateFactory
{
	public delegate Delegate DelegateCreate(LuaFunction func, LuaTable self, bool flag);
	public static Dictionary<Type, DelegateCreate> dict = new Dictionary<Type, DelegateCreate>();
	static DelegateFactory factory = new DelegateFactory();

	public static void Init()
	{
		Register();
	}

	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), factory.System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), factory.UnityEngine_Events_UnityAction);
		dict.Add(typeof(System.Predicate<int>), factory.System_Predicate_int);
		dict.Add(typeof(System.Action<int>), factory.System_Action_int);
		dict.Add(typeof(System.Comparison<int>), factory.System_Comparison_int);
		dict.Add(typeof(System.Func<int,int>), factory.System_Func_int_int);
		dict.Add(typeof(System.Action<UnityEngine.GameObject,int>), factory.System_Action_UnityEngine_GameObject_int);
		dict.Add(typeof(DG.Tweening.TweenCallback), factory.DG_Tweening_TweenCallback);
		dict.Add(typeof(FairyGUI.GTweenCallback), factory.FairyGUI_GTweenCallback);
		dict.Add(typeof(FairyGUI.GTweenCallback1), factory.FairyGUI_GTweenCallback1);
		dict.Add(typeof(System.Func<string[],object>), factory.System_Func_strings_object);
		dict.Add(typeof(FairyGUI.GTree.TreeNodeRenderDelegate), factory.FairyGUI_GTree_TreeNodeRenderDelegate);
		dict.Add(typeof(FairyGUI.GTree.TreeNodeWillExpandDelegate), factory.FairyGUI_GTree_TreeNodeWillExpandDelegate);
		dict.Add(typeof(FairyGUI.ListItemRenderer), factory.FairyGUI_ListItemRenderer);
		dict.Add(typeof(FairyGUI.ListItemProvider), factory.FairyGUI_ListItemProvider);
		dict.Add(typeof(FairyGUI.EventCallback1), factory.FairyGUI_EventCallback1);
		dict.Add(typeof(FairyGUI.EventCallback0), factory.FairyGUI_EventCallback0);
		dict.Add(typeof(FairyGUI.PlayCompleteCallback), factory.FairyGUI_PlayCompleteCallback);
		dict.Add(typeof(FairyGUI.TransitionHook), factory.FairyGUI_TransitionHook);
		dict.Add(typeof(System.Action<FairyGUI.PackageItem>), factory.System_Action_FairyGUI_PackageItem);
		dict.Add(typeof(FairyGUI.UIPackage.LoadResource), factory.FairyGUI_UIPackage_LoadResource);
		dict.Add(typeof(FairyGUI.UIPackage.LoadResourceAsync), factory.FairyGUI_UIPackage_LoadResourceAsync);
		dict.Add(typeof(FairyGUI.UIPackage.CreateObjectCallback), factory.FairyGUI_UIPackage_CreateObjectCallback);
		dict.Add(typeof(FairyGUI.GObjectPool.InitCallbackDelegate), factory.FairyGUI_GObjectPool_InitCallbackDelegate);
		dict.Add(typeof(System.Action<UnityEngine.Texture>), factory.System_Action_UnityEngine_Texture);
		dict.Add(typeof(System.Action<FairyGUI.NTexture>), factory.System_Action_FairyGUI_NTexture);
		dict.Add(typeof(FairyGUI.TimerCallback), factory.FairyGUI_TimerCallback);
		dict.Add(typeof(FairyGUI.UIObjectFactory.GComponentCreator), factory.FairyGUI_UIObjectFactory_GComponentCreator);
		dict.Add(typeof(FairyGUI.UIObjectFactory.GLoaderCreator), factory.FairyGUI_UIObjectFactory_GLoaderCreator);
		dict.Add(typeof(System.Action<FairyGUI.UpdateContext>), factory.System_Action_FairyGUI_UpdateContext);
		dict.Add(typeof(FairyGUI.TreeView.TreeNodeCreateCellDelegate), factory.FairyGUI_TreeView_TreeNodeCreateCellDelegate);
		dict.Add(typeof(FairyGUI.TreeView.TreeNodeRenderDelegate), factory.FairyGUI_TreeView_TreeNodeRenderDelegate);
		dict.Add(typeof(FairyGUI.TreeView.TreeNodeWillExpandDelegate), factory.FairyGUI_TreeView_TreeNodeWillExpandDelegate);

		DelegateTraits<System.Action>.Init(factory.System_Action);
		DelegateTraits<UnityEngine.Events.UnityAction>.Init(factory.UnityEngine_Events_UnityAction);
		DelegateTraits<System.Predicate<int>>.Init(factory.System_Predicate_int);
		DelegateTraits<System.Action<int>>.Init(factory.System_Action_int);
		DelegateTraits<System.Comparison<int>>.Init(factory.System_Comparison_int);
		DelegateTraits<System.Func<int,int>>.Init(factory.System_Func_int_int);
		DelegateTraits<System.Action<UnityEngine.GameObject,int>>.Init(factory.System_Action_UnityEngine_GameObject_int);
		DelegateTraits<DG.Tweening.TweenCallback>.Init(factory.DG_Tweening_TweenCallback);
		DelegateTraits<FairyGUI.GTweenCallback>.Init(factory.FairyGUI_GTweenCallback);
		DelegateTraits<FairyGUI.GTweenCallback1>.Init(factory.FairyGUI_GTweenCallback1);
		DelegateTraits<System.Func<string[],object>>.Init(factory.System_Func_strings_object);
		DelegateTraits<FairyGUI.GTree.TreeNodeRenderDelegate>.Init(factory.FairyGUI_GTree_TreeNodeRenderDelegate);
		DelegateTraits<FairyGUI.GTree.TreeNodeWillExpandDelegate>.Init(factory.FairyGUI_GTree_TreeNodeWillExpandDelegate);
		DelegateTraits<FairyGUI.ListItemRenderer>.Init(factory.FairyGUI_ListItemRenderer);
		DelegateTraits<FairyGUI.ListItemProvider>.Init(factory.FairyGUI_ListItemProvider);
		DelegateTraits<FairyGUI.EventCallback1>.Init(factory.FairyGUI_EventCallback1);
		DelegateTraits<FairyGUI.EventCallback0>.Init(factory.FairyGUI_EventCallback0);
		DelegateTraits<FairyGUI.PlayCompleteCallback>.Init(factory.FairyGUI_PlayCompleteCallback);
		DelegateTraits<FairyGUI.TransitionHook>.Init(factory.FairyGUI_TransitionHook);
		DelegateTraits<System.Action<FairyGUI.PackageItem>>.Init(factory.System_Action_FairyGUI_PackageItem);
		DelegateTraits<FairyGUI.UIPackage.LoadResource>.Init(factory.FairyGUI_UIPackage_LoadResource);
		DelegateTraits<FairyGUI.UIPackage.LoadResourceAsync>.Init(factory.FairyGUI_UIPackage_LoadResourceAsync);
		DelegateTraits<FairyGUI.UIPackage.CreateObjectCallback>.Init(factory.FairyGUI_UIPackage_CreateObjectCallback);
		DelegateTraits<FairyGUI.GObjectPool.InitCallbackDelegate>.Init(factory.FairyGUI_GObjectPool_InitCallbackDelegate);
		DelegateTraits<System.Action<UnityEngine.Texture>>.Init(factory.System_Action_UnityEngine_Texture);
		DelegateTraits<System.Action<FairyGUI.NTexture>>.Init(factory.System_Action_FairyGUI_NTexture);
		DelegateTraits<FairyGUI.TimerCallback>.Init(factory.FairyGUI_TimerCallback);
		DelegateTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Init(factory.FairyGUI_UIObjectFactory_GComponentCreator);
		DelegateTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Init(factory.FairyGUI_UIObjectFactory_GLoaderCreator);
		DelegateTraits<System.Action<FairyGUI.UpdateContext>>.Init(factory.System_Action_FairyGUI_UpdateContext);
		DelegateTraits<FairyGUI.TreeView.TreeNodeCreateCellDelegate>.Init(factory.FairyGUI_TreeView_TreeNodeCreateCellDelegate);
		DelegateTraits<FairyGUI.TreeView.TreeNodeRenderDelegate>.Init(factory.FairyGUI_TreeView_TreeNodeRenderDelegate);
		DelegateTraits<FairyGUI.TreeView.TreeNodeWillExpandDelegate>.Init(factory.FairyGUI_TreeView_TreeNodeWillExpandDelegate);

		TypeTraits<System.Action>.Init(factory.Check_System_Action);
		TypeTraits<UnityEngine.Events.UnityAction>.Init(factory.Check_UnityEngine_Events_UnityAction);
		TypeTraits<System.Predicate<int>>.Init(factory.Check_System_Predicate_int);
		TypeTraits<System.Action<int>>.Init(factory.Check_System_Action_int);
		TypeTraits<System.Comparison<int>>.Init(factory.Check_System_Comparison_int);
		TypeTraits<System.Func<int,int>>.Init(factory.Check_System_Func_int_int);
		TypeTraits<System.Action<UnityEngine.GameObject,int>>.Init(factory.Check_System_Action_UnityEngine_GameObject_int);
		TypeTraits<DG.Tweening.TweenCallback>.Init(factory.Check_DG_Tweening_TweenCallback);
		TypeTraits<FairyGUI.GTweenCallback>.Init(factory.Check_FairyGUI_GTweenCallback);
		TypeTraits<FairyGUI.GTweenCallback1>.Init(factory.Check_FairyGUI_GTweenCallback1);
		TypeTraits<System.Func<string[],object>>.Init(factory.Check_System_Func_strings_object);
		TypeTraits<FairyGUI.GTree.TreeNodeRenderDelegate>.Init(factory.Check_FairyGUI_GTree_TreeNodeRenderDelegate);
		TypeTraits<FairyGUI.GTree.TreeNodeWillExpandDelegate>.Init(factory.Check_FairyGUI_GTree_TreeNodeWillExpandDelegate);
		TypeTraits<FairyGUI.ListItemRenderer>.Init(factory.Check_FairyGUI_ListItemRenderer);
		TypeTraits<FairyGUI.ListItemProvider>.Init(factory.Check_FairyGUI_ListItemProvider);
		TypeTraits<FairyGUI.EventCallback1>.Init(factory.Check_FairyGUI_EventCallback1);
		TypeTraits<FairyGUI.EventCallback0>.Init(factory.Check_FairyGUI_EventCallback0);
		TypeTraits<FairyGUI.PlayCompleteCallback>.Init(factory.Check_FairyGUI_PlayCompleteCallback);
		TypeTraits<FairyGUI.TransitionHook>.Init(factory.Check_FairyGUI_TransitionHook);
		TypeTraits<System.Action<FairyGUI.PackageItem>>.Init(factory.Check_System_Action_FairyGUI_PackageItem);
		TypeTraits<FairyGUI.UIPackage.LoadResource>.Init(factory.Check_FairyGUI_UIPackage_LoadResource);
		TypeTraits<FairyGUI.UIPackage.LoadResourceAsync>.Init(factory.Check_FairyGUI_UIPackage_LoadResourceAsync);
		TypeTraits<FairyGUI.UIPackage.CreateObjectCallback>.Init(factory.Check_FairyGUI_UIPackage_CreateObjectCallback);
		TypeTraits<FairyGUI.GObjectPool.InitCallbackDelegate>.Init(factory.Check_FairyGUI_GObjectPool_InitCallbackDelegate);
		TypeTraits<System.Action<UnityEngine.Texture>>.Init(factory.Check_System_Action_UnityEngine_Texture);
		TypeTraits<System.Action<FairyGUI.NTexture>>.Init(factory.Check_System_Action_FairyGUI_NTexture);
		TypeTraits<FairyGUI.TimerCallback>.Init(factory.Check_FairyGUI_TimerCallback);
		TypeTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Init(factory.Check_FairyGUI_UIObjectFactory_GComponentCreator);
		TypeTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Init(factory.Check_FairyGUI_UIObjectFactory_GLoaderCreator);
		TypeTraits<System.Action<FairyGUI.UpdateContext>>.Init(factory.Check_System_Action_FairyGUI_UpdateContext);
		TypeTraits<FairyGUI.TreeView.TreeNodeCreateCellDelegate>.Init(factory.Check_FairyGUI_TreeView_TreeNodeCreateCellDelegate);
		TypeTraits<FairyGUI.TreeView.TreeNodeRenderDelegate>.Init(factory.Check_FairyGUI_TreeView_TreeNodeRenderDelegate);
		TypeTraits<FairyGUI.TreeView.TreeNodeWillExpandDelegate>.Init(factory.Check_FairyGUI_TreeView_TreeNodeWillExpandDelegate);

		StackTraits<System.Action>.Push = factory.Push_System_Action;
		StackTraits<UnityEngine.Events.UnityAction>.Push = factory.Push_UnityEngine_Events_UnityAction;
		StackTraits<System.Predicate<int>>.Push = factory.Push_System_Predicate_int;
		StackTraits<System.Action<int>>.Push = factory.Push_System_Action_int;
		StackTraits<System.Comparison<int>>.Push = factory.Push_System_Comparison_int;
		StackTraits<System.Func<int,int>>.Push = factory.Push_System_Func_int_int;
		StackTraits<System.Action<UnityEngine.GameObject,int>>.Push = factory.Push_System_Action_UnityEngine_GameObject_int;
		StackTraits<DG.Tweening.TweenCallback>.Push = factory.Push_DG_Tweening_TweenCallback;
		StackTraits<FairyGUI.GTweenCallback>.Push = factory.Push_FairyGUI_GTweenCallback;
		StackTraits<FairyGUI.GTweenCallback1>.Push = factory.Push_FairyGUI_GTweenCallback1;
		StackTraits<System.Func<string[],object>>.Push = factory.Push_System_Func_strings_object;
		StackTraits<FairyGUI.GTree.TreeNodeRenderDelegate>.Push = factory.Push_FairyGUI_GTree_TreeNodeRenderDelegate;
		StackTraits<FairyGUI.GTree.TreeNodeWillExpandDelegate>.Push = factory.Push_FairyGUI_GTree_TreeNodeWillExpandDelegate;
		StackTraits<FairyGUI.ListItemRenderer>.Push = factory.Push_FairyGUI_ListItemRenderer;
		StackTraits<FairyGUI.ListItemProvider>.Push = factory.Push_FairyGUI_ListItemProvider;
		StackTraits<FairyGUI.EventCallback1>.Push = factory.Push_FairyGUI_EventCallback1;
		StackTraits<FairyGUI.EventCallback0>.Push = factory.Push_FairyGUI_EventCallback0;
		StackTraits<FairyGUI.PlayCompleteCallback>.Push = factory.Push_FairyGUI_PlayCompleteCallback;
		StackTraits<FairyGUI.TransitionHook>.Push = factory.Push_FairyGUI_TransitionHook;
		StackTraits<System.Action<FairyGUI.PackageItem>>.Push = factory.Push_System_Action_FairyGUI_PackageItem;
		StackTraits<FairyGUI.UIPackage.LoadResource>.Push = factory.Push_FairyGUI_UIPackage_LoadResource;
		StackTraits<FairyGUI.UIPackage.LoadResourceAsync>.Push = factory.Push_FairyGUI_UIPackage_LoadResourceAsync;
		StackTraits<FairyGUI.UIPackage.CreateObjectCallback>.Push = factory.Push_FairyGUI_UIPackage_CreateObjectCallback;
		StackTraits<FairyGUI.GObjectPool.InitCallbackDelegate>.Push = factory.Push_FairyGUI_GObjectPool_InitCallbackDelegate;
		StackTraits<System.Action<UnityEngine.Texture>>.Push = factory.Push_System_Action_UnityEngine_Texture;
		StackTraits<System.Action<FairyGUI.NTexture>>.Push = factory.Push_System_Action_FairyGUI_NTexture;
		StackTraits<FairyGUI.TimerCallback>.Push = factory.Push_FairyGUI_TimerCallback;
		StackTraits<FairyGUI.UIObjectFactory.GComponentCreator>.Push = factory.Push_FairyGUI_UIObjectFactory_GComponentCreator;
		StackTraits<FairyGUI.UIObjectFactory.GLoaderCreator>.Push = factory.Push_FairyGUI_UIObjectFactory_GLoaderCreator;
		StackTraits<System.Action<FairyGUI.UpdateContext>>.Push = factory.Push_System_Action_FairyGUI_UpdateContext;
		StackTraits<FairyGUI.TreeView.TreeNodeCreateCellDelegate>.Push = factory.Push_FairyGUI_TreeView_TreeNodeCreateCellDelegate;
		StackTraits<FairyGUI.TreeView.TreeNodeRenderDelegate>.Push = factory.Push_FairyGUI_TreeView_TreeNodeRenderDelegate;
		StackTraits<FairyGUI.TreeView.TreeNodeWillExpandDelegate>.Push = factory.Push_FairyGUI_TreeView_TreeNodeWillExpandDelegate;
	}
    
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateCreate Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func);
            
            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }  
            else
            {
                Delegate d = Create(func, null, false);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func);
                return d;
            }       
        }

        return Create(null, null, false);        
    }
    
    public static Delegate CreateDelegate(Type t, LuaFunction func, LuaTable self)
    {
        DelegateCreate Create = null;

        if (!dict.TryGetValue(t, out Create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));
        }

        if (func != null)
        {
            LuaState state = func.GetLuaState();
            LuaDelegate target = state.GetLuaDelegate(func, self);

            if (target != null)
            {
                return Delegate.CreateDelegate(t, target, target.method);
            }
            else
            {
                Delegate d = Create(func, self, true);
                target = d.Target as LuaDelegate;
                state.AddLuaDelegate(target, func, self);
                return d;
            }
        }

        return Create(null, null, true);
    }
    
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }
    
    public static Delegate RemoveDelegate(Delegate obj, Delegate dg)
    {
        LuaDelegate remove = dg.Target as LuaDelegate;

        if (remove == null)
        {
            obj = Delegate.Remove(obj, dg);
            return obj;
        }

        LuaState state = remove.func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();        

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld == remove)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                state.DelayDispose(ld.self);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }
		public System_Action_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action System_Action(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			System_Action_Event target = new System_Action_Event(func);
			System.Action d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_Event target = new System_Action_Event(func, self);
			System.Action d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action), L, pos);
	}

	void Push_System_Action(IntPtr L, System.Action o)
	{
		ToLua.Push(L, o);
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }
		public UnityEngine_Events_UnityAction_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public UnityEngine.Events.UnityAction UnityEngine_Events_UnityAction(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func);
			UnityEngine.Events.UnityAction d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			UnityEngine_Events_UnityAction_Event target = new UnityEngine_Events_UnityAction_Event(func, self);
			UnityEngine.Events.UnityAction d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_UnityEngine_Events_UnityAction(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(UnityEngine.Events.UnityAction), L, pos);
	}

	void Push_UnityEngine_Events_UnityAction(IntPtr L, UnityEngine.Events.UnityAction o)
	{
		ToLua.Push(L, o);
	}

	class System_Predicate_int_Event : LuaDelegate
	{
		public System_Predicate_int_Event(LuaFunction func) : base(func) { }
		public System_Predicate_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public bool Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}

		public bool CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public System.Predicate<int> System_Predicate_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Predicate<int> fn = delegate(int param0) { return false; };
			return fn;
		}

		if(!flag)
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func);
			System.Predicate<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Predicate_int_Event target = new System_Predicate_int_Event(func, self);
			System.Predicate<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Predicate_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Predicate<int>), L, pos);
	}

	void Push_System_Predicate_int(IntPtr L, System.Predicate<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_int_Event : LuaDelegate
	{
		public System_Action_int_Event(LuaFunction func) : base(func) { }
		public System_Action_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<int> System_Action_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<int> fn = delegate(int param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_int_Event target = new System_Action_int_Event(func);
			System.Action<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_int_Event target = new System_Action_int_Event(func, self);
			System.Action<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<int>), L, pos);
	}

	void Push_System_Action_int(IntPtr L, System.Action<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Comparison_int_Event : LuaDelegate
	{
		public System_Comparison_int_Event(LuaFunction func) : base(func) { }
		public System_Comparison_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public System.Comparison<int> System_Comparison_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Comparison<int> fn = delegate(int param0, int param1) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func);
			System.Comparison<int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Comparison_int_Event target = new System_Comparison_int_Event(func, self);
			System.Comparison<int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Comparison_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Comparison<int>), L, pos);
	}

	void Push_System_Comparison_int(IntPtr L, System.Comparison<int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Func_int_int_Event : LuaDelegate
	{
		public System_Func_int_int_Event(LuaFunction func) : base(func) { }
		public System_Func_int_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public int Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}

		public int CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public System.Func<int,int> System_Func_int_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<int,int> fn = delegate(int param0) { return 0; };
			return fn;
		}

		if(!flag)
		{
			System_Func_int_int_Event target = new System_Func_int_int_Event(func);
			System.Func<int,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_int_int_Event target = new System_Func_int_int_Event(func, self);
			System.Func<int,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Func_int_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Func<int,int>), L, pos);
	}

	void Push_System_Func_int_int(IntPtr L, System.Func<int,int> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_UnityEngine_GameObject_int_Event : LuaDelegate
	{
		public System_Action_UnityEngine_GameObject_int_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_GameObject_int_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.GameObject param0, int param1)
		{
			func.BeginPCall();
			func.PushSealed(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.GameObject param0, int param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushSealed(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<UnityEngine.GameObject,int> System_Action_UnityEngine_GameObject_int(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.GameObject,int> fn = delegate(UnityEngine.GameObject param0, int param1) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_GameObject_int_Event target = new System_Action_UnityEngine_GameObject_int_Event(func);
			System.Action<UnityEngine.GameObject,int> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_GameObject_int_Event target = new System_Action_UnityEngine_GameObject_int_Event(func, self);
			System.Action<UnityEngine.GameObject,int> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_UnityEngine_GameObject_int(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<UnityEngine.GameObject,int>), L, pos);
	}

	void Push_System_Action_UnityEngine_GameObject_int(IntPtr L, System.Action<UnityEngine.GameObject,int> o)
	{
		ToLua.Push(L, o);
	}

	class DG_Tweening_TweenCallback_Event : LuaDelegate
	{
		public DG_Tweening_TweenCallback_Event(LuaFunction func) : base(func) { }
		public DG_Tweening_TweenCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public DG.Tweening.TweenCallback DG_Tweening_TweenCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			DG.Tweening.TweenCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			DG_Tweening_TweenCallback_Event target = new DG_Tweening_TweenCallback_Event(func);
			DG.Tweening.TweenCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			DG_Tweening_TweenCallback_Event target = new DG_Tweening_TweenCallback_Event(func, self);
			DG.Tweening.TweenCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_DG_Tweening_TweenCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(DG.Tweening.TweenCallback), L, pos);
	}

	void Push_DG_Tweening_TweenCallback(IntPtr L, DG.Tweening.TweenCallback o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_GTweenCallback_Event : LuaDelegate
	{
		public FairyGUI_GTweenCallback_Event(LuaFunction func) : base(func) { }
		public FairyGUI_GTweenCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.GTweenCallback FairyGUI_GTweenCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.GTweenCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_GTweenCallback_Event target = new FairyGUI_GTweenCallback_Event(func);
			FairyGUI.GTweenCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_GTweenCallback_Event target = new FairyGUI_GTweenCallback_Event(func, self);
			FairyGUI.GTweenCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_GTweenCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.GTweenCallback), L, pos);
	}

	void Push_FairyGUI_GTweenCallback(IntPtr L, FairyGUI.GTweenCallback o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_GTweenCallback1_Event : LuaDelegate
	{
		public FairyGUI_GTweenCallback1_Event(LuaFunction func) : base(func) { }
		public FairyGUI_GTweenCallback1_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.GTweener param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.GTweener param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.GTweenCallback1 FairyGUI_GTweenCallback1(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.GTweenCallback1 fn = delegate(FairyGUI.GTweener param0) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_GTweenCallback1_Event target = new FairyGUI_GTweenCallback1_Event(func);
			FairyGUI.GTweenCallback1 d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_GTweenCallback1_Event target = new FairyGUI_GTweenCallback1_Event(func, self);
			FairyGUI.GTweenCallback1 d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_GTweenCallback1(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.GTweenCallback1), L, pos);
	}

	void Push_FairyGUI_GTweenCallback1(IntPtr L, FairyGUI.GTweenCallback1 o)
	{
		ToLua.Push(L, o);
	}

	class System_Func_strings_object_Event : LuaDelegate
	{
		public System_Func_strings_object_Event(LuaFunction func) : base(func) { }
		public System_Func_strings_object_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public object Call(string[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			object ret = func.CheckVariant();
			func.EndPCall();
			return ret;
		}

		public object CallWithSelf(string[] param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			object ret = func.CheckVariant();
			func.EndPCall();
			return ret;
		}
	}

	public System.Func<string[],object> System_Func_strings_object(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Func<string[],object> fn = delegate(string[] param0) { return null; };
			return fn;
		}

		if(!flag)
		{
			System_Func_strings_object_Event target = new System_Func_strings_object_Event(func);
			System.Func<string[],object> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Func_strings_object_Event target = new System_Func_strings_object_Event(func, self);
			System.Func<string[],object> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Func_strings_object(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Func<string[],object>), L, pos);
	}

	void Push_System_Func_strings_object(IntPtr L, System.Func<string[],object> o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_GTree_TreeNodeRenderDelegate_Event : LuaDelegate
	{
		public FairyGUI_GTree_TreeNodeRenderDelegate_Event(LuaFunction func) : base(func) { }
		public FairyGUI_GTree_TreeNodeRenderDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.GTreeNode param0, FairyGUI.GComponent param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.GTreeNode param0, FairyGUI.GComponent param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.GTree.TreeNodeRenderDelegate FairyGUI_GTree_TreeNodeRenderDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.GTree.TreeNodeRenderDelegate fn = delegate(FairyGUI.GTreeNode param0, FairyGUI.GComponent param1) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_GTree_TreeNodeRenderDelegate_Event target = new FairyGUI_GTree_TreeNodeRenderDelegate_Event(func);
			FairyGUI.GTree.TreeNodeRenderDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_GTree_TreeNodeRenderDelegate_Event target = new FairyGUI_GTree_TreeNodeRenderDelegate_Event(func, self);
			FairyGUI.GTree.TreeNodeRenderDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_GTree_TreeNodeRenderDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.GTree.TreeNodeRenderDelegate), L, pos);
	}

	void Push_FairyGUI_GTree_TreeNodeRenderDelegate(IntPtr L, FairyGUI.GTree.TreeNodeRenderDelegate o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_GTree_TreeNodeWillExpandDelegate_Event : LuaDelegate
	{
		public FairyGUI_GTree_TreeNodeWillExpandDelegate_Event(LuaFunction func) : base(func) { }
		public FairyGUI_GTree_TreeNodeWillExpandDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.GTreeNode param0, bool param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.GTreeNode param0, bool param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.GTree.TreeNodeWillExpandDelegate FairyGUI_GTree_TreeNodeWillExpandDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.GTree.TreeNodeWillExpandDelegate fn = delegate(FairyGUI.GTreeNode param0, bool param1) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_GTree_TreeNodeWillExpandDelegate_Event target = new FairyGUI_GTree_TreeNodeWillExpandDelegate_Event(func);
			FairyGUI.GTree.TreeNodeWillExpandDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_GTree_TreeNodeWillExpandDelegate_Event target = new FairyGUI_GTree_TreeNodeWillExpandDelegate_Event(func, self);
			FairyGUI.GTree.TreeNodeWillExpandDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_GTree_TreeNodeWillExpandDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.GTree.TreeNodeWillExpandDelegate), L, pos);
	}

	void Push_FairyGUI_GTree_TreeNodeWillExpandDelegate(IntPtr L, FairyGUI.GTree.TreeNodeWillExpandDelegate o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_ListItemRenderer_Event : LuaDelegate
	{
		public FairyGUI_ListItemRenderer_Event(LuaFunction func) : base(func) { }
		public FairyGUI_ListItemRenderer_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(int param0, FairyGUI.GObject param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(int param0, FairyGUI.GObject param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PushObject(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.ListItemRenderer FairyGUI_ListItemRenderer(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.ListItemRenderer fn = delegate(int param0, FairyGUI.GObject param1) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_ListItemRenderer_Event target = new FairyGUI_ListItemRenderer_Event(func);
			FairyGUI.ListItemRenderer d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_ListItemRenderer_Event target = new FairyGUI_ListItemRenderer_Event(func, self);
			FairyGUI.ListItemRenderer d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_ListItemRenderer(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.ListItemRenderer), L, pos);
	}

	void Push_FairyGUI_ListItemRenderer(IntPtr L, FairyGUI.ListItemRenderer o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_ListItemProvider_Event : LuaDelegate
	{
		public FairyGUI_ListItemProvider_Event(LuaFunction func) : base(func) { }
		public FairyGUI_ListItemProvider_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public string Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			string ret = func.CheckString();
			func.EndPCall();
			return ret;
		}

		public string CallWithSelf(int param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			string ret = func.CheckString();
			func.EndPCall();
			return ret;
		}
	}

	public FairyGUI.ListItemProvider FairyGUI_ListItemProvider(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.ListItemProvider fn = delegate(int param0) { return null; };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_ListItemProvider_Event target = new FairyGUI_ListItemProvider_Event(func);
			FairyGUI.ListItemProvider d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_ListItemProvider_Event target = new FairyGUI_ListItemProvider_Event(func, self);
			FairyGUI.ListItemProvider d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_ListItemProvider(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.ListItemProvider), L, pos);
	}

	void Push_FairyGUI_ListItemProvider(IntPtr L, FairyGUI.ListItemProvider o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_EventCallback1_Event : LuaDelegate
	{
		public FairyGUI_EventCallback1_Event(LuaFunction func) : base(func) { }
		public FairyGUI_EventCallback1_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.EventContext param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.EventContext param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.EventCallback1 FairyGUI_EventCallback1(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.EventCallback1 fn = delegate(FairyGUI.EventContext param0) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_EventCallback1_Event target = new FairyGUI_EventCallback1_Event(func);
			FairyGUI.EventCallback1 d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_EventCallback1_Event target = new FairyGUI_EventCallback1_Event(func, self);
			FairyGUI.EventCallback1 d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_EventCallback1(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.EventCallback1), L, pos);
	}

	void Push_FairyGUI_EventCallback1(IntPtr L, FairyGUI.EventCallback1 o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_EventCallback0_Event : LuaDelegate
	{
		public FairyGUI_EventCallback0_Event(LuaFunction func) : base(func) { }
		public FairyGUI_EventCallback0_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.EventCallback0 FairyGUI_EventCallback0(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.EventCallback0 fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_EventCallback0_Event target = new FairyGUI_EventCallback0_Event(func);
			FairyGUI.EventCallback0 d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_EventCallback0_Event target = new FairyGUI_EventCallback0_Event(func, self);
			FairyGUI.EventCallback0 d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_EventCallback0(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.EventCallback0), L, pos);
	}

	void Push_FairyGUI_EventCallback0(IntPtr L, FairyGUI.EventCallback0 o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_PlayCompleteCallback_Event : LuaDelegate
	{
		public FairyGUI_PlayCompleteCallback_Event(LuaFunction func) : base(func) { }
		public FairyGUI_PlayCompleteCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.PlayCompleteCallback FairyGUI_PlayCompleteCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.PlayCompleteCallback fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_PlayCompleteCallback_Event target = new FairyGUI_PlayCompleteCallback_Event(func);
			FairyGUI.PlayCompleteCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_PlayCompleteCallback_Event target = new FairyGUI_PlayCompleteCallback_Event(func, self);
			FairyGUI.PlayCompleteCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_PlayCompleteCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.PlayCompleteCallback), L, pos);
	}

	void Push_FairyGUI_PlayCompleteCallback(IntPtr L, FairyGUI.PlayCompleteCallback o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_TransitionHook_Event : LuaDelegate
	{
		public FairyGUI_TransitionHook_Event(LuaFunction func) : base(func) { }
		public FairyGUI_TransitionHook_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call()
		{
			func.Call();
		}

		public void CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.TransitionHook FairyGUI_TransitionHook(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.TransitionHook fn = delegate() { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_TransitionHook_Event target = new FairyGUI_TransitionHook_Event(func);
			FairyGUI.TransitionHook d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_TransitionHook_Event target = new FairyGUI_TransitionHook_Event(func, self);
			FairyGUI.TransitionHook d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_TransitionHook(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.TransitionHook), L, pos);
	}

	void Push_FairyGUI_TransitionHook(IntPtr L, FairyGUI.TransitionHook o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_FairyGUI_PackageItem_Event : LuaDelegate
	{
		public System_Action_FairyGUI_PackageItem_Event(LuaFunction func) : base(func) { }
		public System_Action_FairyGUI_PackageItem_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.PackageItem param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.PackageItem param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<FairyGUI.PackageItem> System_Action_FairyGUI_PackageItem(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<FairyGUI.PackageItem> fn = delegate(FairyGUI.PackageItem param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_FairyGUI_PackageItem_Event target = new System_Action_FairyGUI_PackageItem_Event(func);
			System.Action<FairyGUI.PackageItem> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_FairyGUI_PackageItem_Event target = new System_Action_FairyGUI_PackageItem_Event(func, self);
			System.Action<FairyGUI.PackageItem> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_FairyGUI_PackageItem(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<FairyGUI.PackageItem>), L, pos);
	}

	void Push_System_Action_FairyGUI_PackageItem(IntPtr L, System.Action<FairyGUI.PackageItem> o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_UIPackage_LoadResource_Event : LuaDelegate
	{
		public FairyGUI_UIPackage_LoadResource_Event(LuaFunction func) : base(func) { }
		public FairyGUI_UIPackage_LoadResource_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public object Call(string param0, string param1, System.Type param2, out FairyGUI.DestroyMethod param3)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			object ret = func.CheckVariant();
			param3 = (FairyGUI.DestroyMethod)func.CheckObject(typeof(FairyGUI.DestroyMethod));
			func.EndPCall();
			return ret;
		}

		public object CallWithSelf(string param0, string param1, System.Type param2, out FairyGUI.DestroyMethod param3)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			object ret = func.CheckVariant();
			param3 = (FairyGUI.DestroyMethod)func.CheckObject(typeof(FairyGUI.DestroyMethod));
			func.EndPCall();
			return ret;
		}
	}

	public FairyGUI.UIPackage.LoadResource FairyGUI_UIPackage_LoadResource(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.UIPackage.LoadResource fn = delegate(string param0, string param1, System.Type param2, out FairyGUI.DestroyMethod param3) 
			{
				param3 = default(FairyGUI.DestroyMethod);
			return null;			};

			return fn;
		}

		if(!flag)
		{
			FairyGUI_UIPackage_LoadResource_Event target = new FairyGUI_UIPackage_LoadResource_Event(func);
			FairyGUI.UIPackage.LoadResource d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_UIPackage_LoadResource_Event target = new FairyGUI_UIPackage_LoadResource_Event(func, self);
			FairyGUI.UIPackage.LoadResource d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_UIPackage_LoadResource(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.UIPackage.LoadResource), L, pos);
	}

	void Push_FairyGUI_UIPackage_LoadResource(IntPtr L, FairyGUI.UIPackage.LoadResource o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_UIPackage_LoadResourceAsync_Event : LuaDelegate
	{
		public FairyGUI_UIPackage_LoadResourceAsync_Event(LuaFunction func) : base(func) { }
		public FairyGUI_UIPackage_LoadResourceAsync_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(string param0, string param1, System.Type param2, FairyGUI.PackageItem param3)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PushObject(param3);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(string param0, string param1, System.Type param2, FairyGUI.PackageItem param3)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PushObject(param3);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.UIPackage.LoadResourceAsync FairyGUI_UIPackage_LoadResourceAsync(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.UIPackage.LoadResourceAsync fn = delegate(string param0, string param1, System.Type param2, FairyGUI.PackageItem param3) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_UIPackage_LoadResourceAsync_Event target = new FairyGUI_UIPackage_LoadResourceAsync_Event(func);
			FairyGUI.UIPackage.LoadResourceAsync d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_UIPackage_LoadResourceAsync_Event target = new FairyGUI_UIPackage_LoadResourceAsync_Event(func, self);
			FairyGUI.UIPackage.LoadResourceAsync d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_UIPackage_LoadResourceAsync(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.UIPackage.LoadResourceAsync), L, pos);
	}

	void Push_FairyGUI_UIPackage_LoadResourceAsync(IntPtr L, FairyGUI.UIPackage.LoadResourceAsync o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_UIPackage_CreateObjectCallback_Event : LuaDelegate
	{
		public FairyGUI_UIPackage_CreateObjectCallback_Event(LuaFunction func) : base(func) { }
		public FairyGUI_UIPackage_CreateObjectCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.GObject param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.GObject param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.UIPackage.CreateObjectCallback FairyGUI_UIPackage_CreateObjectCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.UIPackage.CreateObjectCallback fn = delegate(FairyGUI.GObject param0) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_UIPackage_CreateObjectCallback_Event target = new FairyGUI_UIPackage_CreateObjectCallback_Event(func);
			FairyGUI.UIPackage.CreateObjectCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_UIPackage_CreateObjectCallback_Event target = new FairyGUI_UIPackage_CreateObjectCallback_Event(func, self);
			FairyGUI.UIPackage.CreateObjectCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_UIPackage_CreateObjectCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.UIPackage.CreateObjectCallback), L, pos);
	}

	void Push_FairyGUI_UIPackage_CreateObjectCallback(IntPtr L, FairyGUI.UIPackage.CreateObjectCallback o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_GObjectPool_InitCallbackDelegate_Event : LuaDelegate
	{
		public FairyGUI_GObjectPool_InitCallbackDelegate_Event(LuaFunction func) : base(func) { }
		public FairyGUI_GObjectPool_InitCallbackDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.GObject param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.GObject param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.GObjectPool.InitCallbackDelegate FairyGUI_GObjectPool_InitCallbackDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.GObjectPool.InitCallbackDelegate fn = delegate(FairyGUI.GObject param0) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_GObjectPool_InitCallbackDelegate_Event target = new FairyGUI_GObjectPool_InitCallbackDelegate_Event(func);
			FairyGUI.GObjectPool.InitCallbackDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_GObjectPool_InitCallbackDelegate_Event target = new FairyGUI_GObjectPool_InitCallbackDelegate_Event(func, self);
			FairyGUI.GObjectPool.InitCallbackDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_GObjectPool_InitCallbackDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.GObjectPool.InitCallbackDelegate), L, pos);
	}

	void Push_FairyGUI_GObjectPool_InitCallbackDelegate(IntPtr L, FairyGUI.GObjectPool.InitCallbackDelegate o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_UnityEngine_Texture_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Texture_Event(LuaFunction func) : base(func) { }
		public System_Action_UnityEngine_Texture_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(UnityEngine.Texture param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(UnityEngine.Texture param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<UnityEngine.Texture> System_Action_UnityEngine_Texture(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Texture> fn = delegate(UnityEngine.Texture param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_UnityEngine_Texture_Event target = new System_Action_UnityEngine_Texture_Event(func);
			System.Action<UnityEngine.Texture> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_UnityEngine_Texture_Event target = new System_Action_UnityEngine_Texture_Event(func, self);
			System.Action<UnityEngine.Texture> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_UnityEngine_Texture(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<UnityEngine.Texture>), L, pos);
	}

	void Push_System_Action_UnityEngine_Texture(IntPtr L, System.Action<UnityEngine.Texture> o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_FairyGUI_NTexture_Event : LuaDelegate
	{
		public System_Action_FairyGUI_NTexture_Event(LuaFunction func) : base(func) { }
		public System_Action_FairyGUI_NTexture_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.NTexture param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.NTexture param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<FairyGUI.NTexture> System_Action_FairyGUI_NTexture(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<FairyGUI.NTexture> fn = delegate(FairyGUI.NTexture param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_FairyGUI_NTexture_Event target = new System_Action_FairyGUI_NTexture_Event(func);
			System.Action<FairyGUI.NTexture> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_FairyGUI_NTexture_Event target = new System_Action_FairyGUI_NTexture_Event(func, self);
			System.Action<FairyGUI.NTexture> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_FairyGUI_NTexture(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<FairyGUI.NTexture>), L, pos);
	}

	void Push_System_Action_FairyGUI_NTexture(IntPtr L, System.Action<FairyGUI.NTexture> o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_TimerCallback_Event : LuaDelegate
	{
		public FairyGUI_TimerCallback_Event(LuaFunction func) : base(func) { }
		public FairyGUI_TimerCallback_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(object param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.TimerCallback FairyGUI_TimerCallback(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.TimerCallback fn = delegate(object param0) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_TimerCallback_Event target = new FairyGUI_TimerCallback_Event(func);
			FairyGUI.TimerCallback d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_TimerCallback_Event target = new FairyGUI_TimerCallback_Event(func, self);
			FairyGUI.TimerCallback d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_TimerCallback(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.TimerCallback), L, pos);
	}

	void Push_FairyGUI_TimerCallback(IntPtr L, FairyGUI.TimerCallback o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_UIObjectFactory_GComponentCreator_Event : LuaDelegate
	{
		public FairyGUI_UIObjectFactory_GComponentCreator_Event(LuaFunction func) : base(func) { }
		public FairyGUI_UIObjectFactory_GComponentCreator_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public FairyGUI.GComponent Call()
		{
			func.BeginPCall();
			func.PCall();
			FairyGUI.GComponent ret = (FairyGUI.GComponent)func.CheckObject(typeof(FairyGUI.GComponent));
			func.EndPCall();
			return ret;
		}

		public FairyGUI.GComponent CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			FairyGUI.GComponent ret = (FairyGUI.GComponent)func.CheckObject(typeof(FairyGUI.GComponent));
			func.EndPCall();
			return ret;
		}
	}

	public FairyGUI.UIObjectFactory.GComponentCreator FairyGUI_UIObjectFactory_GComponentCreator(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.UIObjectFactory.GComponentCreator fn = delegate() { return null; };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_UIObjectFactory_GComponentCreator_Event target = new FairyGUI_UIObjectFactory_GComponentCreator_Event(func);
			FairyGUI.UIObjectFactory.GComponentCreator d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_UIObjectFactory_GComponentCreator_Event target = new FairyGUI_UIObjectFactory_GComponentCreator_Event(func, self);
			FairyGUI.UIObjectFactory.GComponentCreator d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_UIObjectFactory_GComponentCreator(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.UIObjectFactory.GComponentCreator), L, pos);
	}

	void Push_FairyGUI_UIObjectFactory_GComponentCreator(IntPtr L, FairyGUI.UIObjectFactory.GComponentCreator o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_UIObjectFactory_GLoaderCreator_Event : LuaDelegate
	{
		public FairyGUI_UIObjectFactory_GLoaderCreator_Event(LuaFunction func) : base(func) { }
		public FairyGUI_UIObjectFactory_GLoaderCreator_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public FairyGUI.GLoader Call()
		{
			func.BeginPCall();
			func.PCall();
			FairyGUI.GLoader ret = (FairyGUI.GLoader)func.CheckObject(typeof(FairyGUI.GLoader));
			func.EndPCall();
			return ret;
		}

		public FairyGUI.GLoader CallWithSelf()
		{
			func.BeginPCall();
			func.Push(self);
			func.PCall();
			FairyGUI.GLoader ret = (FairyGUI.GLoader)func.CheckObject(typeof(FairyGUI.GLoader));
			func.EndPCall();
			return ret;
		}
	}

	public FairyGUI.UIObjectFactory.GLoaderCreator FairyGUI_UIObjectFactory_GLoaderCreator(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.UIObjectFactory.GLoaderCreator fn = delegate() { return null; };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_UIObjectFactory_GLoaderCreator_Event target = new FairyGUI_UIObjectFactory_GLoaderCreator_Event(func);
			FairyGUI.UIObjectFactory.GLoaderCreator d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_UIObjectFactory_GLoaderCreator_Event target = new FairyGUI_UIObjectFactory_GLoaderCreator_Event(func, self);
			FairyGUI.UIObjectFactory.GLoaderCreator d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_UIObjectFactory_GLoaderCreator(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.UIObjectFactory.GLoaderCreator), L, pos);
	}

	void Push_FairyGUI_UIObjectFactory_GLoaderCreator(IntPtr L, FairyGUI.UIObjectFactory.GLoaderCreator o)
	{
		ToLua.Push(L, o);
	}

	class System_Action_FairyGUI_UpdateContext_Event : LuaDelegate
	{
		public System_Action_FairyGUI_UpdateContext_Event(LuaFunction func) : base(func) { }
		public System_Action_FairyGUI_UpdateContext_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.UpdateContext param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.UpdateContext param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public System.Action<FairyGUI.UpdateContext> System_Action_FairyGUI_UpdateContext(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			System.Action<FairyGUI.UpdateContext> fn = delegate(FairyGUI.UpdateContext param0) { };
			return fn;
		}

		if(!flag)
		{
			System_Action_FairyGUI_UpdateContext_Event target = new System_Action_FairyGUI_UpdateContext_Event(func);
			System.Action<FairyGUI.UpdateContext> d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			System_Action_FairyGUI_UpdateContext_Event target = new System_Action_FairyGUI_UpdateContext_Event(func, self);
			System.Action<FairyGUI.UpdateContext> d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_System_Action_FairyGUI_UpdateContext(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(System.Action<FairyGUI.UpdateContext>), L, pos);
	}

	void Push_System_Action_FairyGUI_UpdateContext(IntPtr L, System.Action<FairyGUI.UpdateContext> o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event : LuaDelegate
	{
		public FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event(LuaFunction func) : base(func) { }
		public FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public FairyGUI.GComponent Call(FairyGUI.TreeNode param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			FairyGUI.GComponent ret = (FairyGUI.GComponent)func.CheckObject(typeof(FairyGUI.GComponent));
			func.EndPCall();
			return ret;
		}

		public FairyGUI.GComponent CallWithSelf(FairyGUI.TreeNode param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			FairyGUI.GComponent ret = (FairyGUI.GComponent)func.CheckObject(typeof(FairyGUI.GComponent));
			func.EndPCall();
			return ret;
		}
	}

	public FairyGUI.TreeView.TreeNodeCreateCellDelegate FairyGUI_TreeView_TreeNodeCreateCellDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.TreeView.TreeNodeCreateCellDelegate fn = delegate(FairyGUI.TreeNode param0) { return null; };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event target = new FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event(func);
			FairyGUI.TreeView.TreeNodeCreateCellDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event target = new FairyGUI_TreeView_TreeNodeCreateCellDelegate_Event(func, self);
			FairyGUI.TreeView.TreeNodeCreateCellDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_TreeView_TreeNodeCreateCellDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.TreeView.TreeNodeCreateCellDelegate), L, pos);
	}

	void Push_FairyGUI_TreeView_TreeNodeCreateCellDelegate(IntPtr L, FairyGUI.TreeView.TreeNodeCreateCellDelegate o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_TreeView_TreeNodeRenderDelegate_Event : LuaDelegate
	{
		public FairyGUI_TreeView_TreeNodeRenderDelegate_Event(LuaFunction func) : base(func) { }
		public FairyGUI_TreeView_TreeNodeRenderDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.TreeNode param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.TreeNode param0)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.TreeView.TreeNodeRenderDelegate FairyGUI_TreeView_TreeNodeRenderDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.TreeView.TreeNodeRenderDelegate fn = delegate(FairyGUI.TreeNode param0) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_TreeView_TreeNodeRenderDelegate_Event target = new FairyGUI_TreeView_TreeNodeRenderDelegate_Event(func);
			FairyGUI.TreeView.TreeNodeRenderDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_TreeView_TreeNodeRenderDelegate_Event target = new FairyGUI_TreeView_TreeNodeRenderDelegate_Event(func, self);
			FairyGUI.TreeView.TreeNodeRenderDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_TreeView_TreeNodeRenderDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.TreeView.TreeNodeRenderDelegate), L, pos);
	}

	void Push_FairyGUI_TreeView_TreeNodeRenderDelegate(IntPtr L, FairyGUI.TreeView.TreeNodeRenderDelegate o)
	{
		ToLua.Push(L, o);
	}

	class FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event : LuaDelegate
	{
		public FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event(LuaFunction func) : base(func) { }
		public FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event(LuaFunction func, LuaTable self) : base(func, self) { }

		public void Call(FairyGUI.TreeNode param0, bool param1)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}

		public void CallWithSelf(FairyGUI.TreeNode param0, bool param1)
		{
			func.BeginPCall();
			func.Push(self);
			func.PushObject(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public FairyGUI.TreeView.TreeNodeWillExpandDelegate FairyGUI_TreeView_TreeNodeWillExpandDelegate(LuaFunction func, LuaTable self, bool flag)
	{
		if (func == null)
		{
			FairyGUI.TreeView.TreeNodeWillExpandDelegate fn = delegate(FairyGUI.TreeNode param0, bool param1) { };
			return fn;
		}

		if(!flag)
		{
			FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event target = new FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event(func);
			FairyGUI.TreeView.TreeNodeWillExpandDelegate d = target.Call;
			target.method = d.Method;
			return d;
		}
		else
		{
			FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event target = new FairyGUI_TreeView_TreeNodeWillExpandDelegate_Event(func, self);
			FairyGUI.TreeView.TreeNodeWillExpandDelegate d = target.CallWithSelf;
			target.method = d.Method;
			return d;
		}
	}

	bool Check_FairyGUI_TreeView_TreeNodeWillExpandDelegate(IntPtr L, int pos)
	{
		return TypeChecker.CheckDelegateType(typeof(FairyGUI.TreeView.TreeNodeWillExpandDelegate), L, pos);
	}

	void Push_FairyGUI_TreeView_TreeNodeWillExpandDelegate(IntPtr L, FairyGUI.TreeView.TreeNodeWillExpandDelegate o)
	{
		ToLua.Push(L, o);
	}

}

