//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class FairyGUI_FillTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(FairyGUI.FillType));
		L.RegVar("None", get_None, null);
		L.RegVar("Scale", get_Scale, null);
		L.RegVar("ScaleMatchHeight", get_ScaleMatchHeight, null);
		L.RegVar("ScaleMatchWidth", get_ScaleMatchWidth, null);
		L.RegVar("ScaleFree", get_ScaleFree, null);
		L.RegVar("ScaleNoBorder", get_ScaleNoBorder, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<FairyGUI.FillType>.Check = CheckType;
		StackTraits<FairyGUI.FillType>.Push = Push;
	}

	static void Push(IntPtr L, FairyGUI.FillType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(FairyGUI.FillType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Scale(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillType.Scale);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleMatchHeight(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillType.ScaleMatchHeight);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleMatchWidth(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillType.ScaleMatchWidth);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleFree(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillType.ScaleFree);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScaleNoBorder(IntPtr L)
	{
		ToLua.Push(L, FairyGUI.FillType.ScaleNoBorder);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		FairyGUI.FillType o = (FairyGUI.FillType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

