using UnityEngine;

namespace DG.Tweening.Core
{
	/// <summary>
	/// Public so it can be used by lose scripts related to DOTween (like DOTweenAnimation)
	/// </summary>
	public static class Debugger
	{
		private static int _logPriority;

		private const string _LogPrefix = "<color=#0099bc><b>DOTWEEN ► </b></color>";

		public static int logPriority => _logPriority;

		public static void Log(object message)
		{
			message = string.Concat("<color=#0099bc><b>DOTWEEN ► </b></color>", message?.ToString());
			if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, message))
			{
				Debug.Log(message);
			}
		}

		public static void LogWarning(object message, Tween t = null)
		{
			message = string.Concat("<color=#0099bc><b>DOTWEEN ► </b></color>", message?.ToString());
			if (DOTween.debugMode && t != null)
			{
				bool flag = t.debugTargetId != null;
				bool flag2 = t.stringId != null;
				bool flag3 = t.intId != -999;
				if (flag || flag2 || flag3)
				{
					message = string.Concat(message?.ToString(), "\n");
					if (flag)
					{
						message = string.Concat(message?.ToString(), $"-[debug target ID: {t.debugTargetId}]-");
					}
					if (flag2)
					{
						message = string.Concat(message?.ToString(), $"-[stringId: {t.stringId}]-");
					}
					if (flag3)
					{
						message = string.Concat(message?.ToString(), $"-[intId: {t.intId}]-");
					}
				}
			}
			if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Warning, message))
			{
				Debug.LogWarning(message);
			}
		}

		public static void LogError(object message)
		{
			message = string.Concat("<color=#0099bc><b>DOTWEEN ► </b></color>", message?.ToString());
			if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Error, message))
			{
				Debug.LogError(message);
			}
		}

		public static void LogReport(object message)
		{
			message = string.Format("<color=#00B500FF>{0} REPORT ►</color> {1}", "<color=#0099bc><b>DOTWEEN ► </b></color>", message);
			if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, message))
			{
				Debug.Log(message);
			}
		}

		public static void LogSafeModeReport(object message)
		{
			message = string.Format("<color=#ff7337>{0} SAFE MODE ►</color> {1}", "<color=#0099bc><b>DOTWEEN ► </b></color>", message);
			if (DOTween.onWillLog == null || DOTween.onWillLog(LogType.Log, message))
			{
				Debug.LogWarning(message);
			}
		}

		public static void LogInvalidTween(Tween t)
		{
			LogWarning("This Tween has been killed and is now invalid");
		}

		public static void LogNestedTween(Tween t)
		{
			LogWarning("This Tween was added to a Sequence and can't be controlled directly", t);
		}

		public static void LogNullTween(Tween t)
		{
			LogWarning("Null Tween");
		}

		public static void LogNonPathTween(Tween t)
		{
			LogWarning("This Tween is not a path tween", t);
		}

		public static void LogMissingMaterialProperty(string propertyName)
		{
			LogWarning($"This material doesn't have a {propertyName} property");
		}

		public static void LogMissingMaterialProperty(int propertyId)
		{
			LogWarning($"This material doesn't have a {propertyId} property ID");
		}

		public static void LogRemoveActiveTweenError(string errorInfo, Tween t)
		{
			LogWarning($"Error in RemoveActiveTween ({errorInfo}). It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it (it's very rare and he can't reproduce it) so it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", t);
		}

		public static void LogAddActiveTweenError(string errorInfo, Tween t)
		{
			LogWarning($"Error in AddActiveTween ({errorInfo}). It's been taken care of so no problems, but Daniele (DOTween's author) is trying to pinpoint it (it's very rare and he can't reproduce it) so it would be awesome if you could reproduce this log in a sample project and send it to him. Or even just write him the complete log that was generated by this message. Fixing this would make DOTween slightly faster. Thanks.", t);
		}

		public static void SetLogPriority(LogBehaviour logBehaviour)
		{
			switch (logBehaviour)
			{
			case LogBehaviour.Default:
				_logPriority = 1;
				break;
			case LogBehaviour.Verbose:
				_logPriority = 2;
				break;
			default:
				_logPriority = 0;
				break;
			}
		}
	}
}
