name: Delete Main Doc

on:
  pull_request:
    types:
      - closed

jobs:
  delete-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Delete Doc on main branch
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          PR_BRANCH=$(git log -1 --pretty=format:'%s' | grep -oP 'Merge pull request #\K[0-9]+')
          BASE_BRANCH=$(git show -s --format=%H main)

          if [ "${BASE_BRANCH}" == "${PR_BRANCH}" ]; then
            rm Documentation~/CHANGELOG.md CHANGELOG.md
            rm Documentation~/CODE_OF_CONDUCT.md CODE_OF_CONDUCT.md
            rm Documentation~/CODINGSTANDARD.md CODINGSTANDARD.md
            rm Documentation~/CONTRIBUTING.md CONTRIBUTING.md
            rm Documentation~/LICENSE.md LICENSE.md
            rm Documentation~/README.md README.md
            rm Documentation~/README_EN.md README_EN.md
            rm Documentation~/SECURITY.md SECURITY.md
            git add Documentation~/CHANGELOG.md CHANGELOG.md
            git add Documentation~/CODE_OF_CONDUCT.md CODE_OF_CONDUCT.md
            git add Documentation~/CODINGSTANDARD.md CODINGSTANDARD.md
            git add Documentation~/CONTRIBUTING.md CONTRIBUTING.md
            git add Documentation~/LICENSE.md LICENSE.md
            git add Documentation~/README.md README.md
            git add Documentation~/README_EN.md README_EN.md
            git add Documentation~/SECURITY.md SECURITY.md
            git commit -m "Delete Main Doc" || true
            git push
          fi
        fi
