name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Sync Github Repos To Git Code Tencent  # 名字随便起
      uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
      with:
        src: github/1398581458@qq.com  # 源端账户名(github)
        dst: git.code.tencent.com/Xinansky  # 目的端账户名(gitee)
        dst_key: ${{ secrets.TENCENTGIT_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.TENCENTGIT_TOKEN }}  # Gitee账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "com.aio.package"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作
