// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NBool
    { 
        /// <param name="a"> <see cref="NBool"/> </param>
        /// <param name="b"> <see cref="NBool"/> </param>
        public static bool operator ==(NBool a, NBool b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NBool"/> </param>
        /// <param name="b"> <see cref="bool"/> </param>
        public static bool operator ==(NBool a, bool b) => a.Value == b;

        /// <param name="a"> <see cref="NBool"/> </param>
        /// <param name="b"> <see cref="NBool"/> </param>
        public static bool operator !=(NBool a, NBool b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NBool"/> </param>
        /// <param name="b"> <see cref="bool"/> </param>
        public static bool operator !=(NBool a, bool b) => a.Value != b;
    }
}
