// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.InteropServices;

namespace AIO.Security
{
    [Serializable, ComVisible(true)]
    partial struct NByte
    {
        /// <param name="value"> <see cref="byte"/> </param>
        public static implicit operator NByte(byte value) => new NByte(value);

        /// <param name="value"> <see cref="NByte"/> </param>
        public static implicit operator byte(NByte value) => value.Value;
    }
}
