// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NChar
    { 
        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="NChar"/> </param>
        public static bool operator ==(NChar a, NChar b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="char"/> </param>
        public static bool operator ==(NChar a, char b) => a.Value == b;

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="NChar"/> </param>
        public static bool operator !=(NChar a, NChar b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="char"/> </param>
        public static bool operator !=(NChar a, char b) => a.Value != b;
        /// <param name="a"> <see cref="NChar"/> </param>
        public static NChar operator --(NChar a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NChar"/> </param>
        public static NChar operator ++(NChar a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="NChar"/> </param>
        public static NChar operator +(NChar a, NChar b) => new NChar(a.Value + b.Value);

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="char"/> </param>
        public static NChar operator +(NChar a, char b) => new NChar(a.Value + b);

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="NChar"/> </param>
        public static NChar operator -(NChar a, NChar b) => new NChar(a.Value - b.Value);

        /// <param name="a"> <see cref="NChar"/> </param>
        /// <param name="b"> <see cref="char"/> </param>
        public static NChar operator -(NChar a, char b) => new NChar(a.Value - b);
    }
}
