// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NDecimal
    { 
        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="NDecimal"/> </param>
        public static bool operator ==(NDecimal a, NDecimal b) => Math.Abs(a.Value - b.Value) <= decimal.Zero;

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="decimal"/> </param>
        public static bool operator ==(NDecimal a, decimal b) => Math.Abs(a.Value - b) <= decimal.Zero;

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="NDecimal"/> </param>
        public static bool operator !=(NDecimal a, NDecimal b) => Math.Abs(a.Value - b.Value) > decimal.Zero;

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="decimal"/> </param>
        public static bool operator !=(NDecimal a, decimal b) => Math.Abs(a.Value - b) > decimal.Zero;
        /// <param name="a"> <see cref="NDecimal"/> </param>
        public static NDecimal operator --(NDecimal a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NDecimal"/> </param>
        public static NDecimal operator ++(NDecimal a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="NDecimal"/> </param>
        public static NDecimal operator +(NDecimal a, NDecimal b) => new NDecimal(a.Value + b.Value);

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="decimal"/> </param>
        public static NDecimal operator +(NDecimal a, decimal b) => new NDecimal(a.Value + b);

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="NDecimal"/> </param>
        public static NDecimal operator -(NDecimal a, NDecimal b) => new NDecimal(a.Value - b.Value);

        /// <param name="a"> <see cref="NDecimal"/> </param>
        /// <param name="b"> <see cref="decimal"/> </param>
        public static NDecimal operator -(NDecimal a, decimal b) => new NDecimal(a.Value - b);
    }
}
