// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NSByte
    { 
        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="NSByte"/> </param>
        public static bool operator ==(NSByte a, NSByte b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="sbyte"/> </param>
        public static bool operator ==(NSByte a, sbyte b) => a.Value == b;

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="NSByte"/> </param>
        public static bool operator !=(NSByte a, NSByte b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="sbyte"/> </param>
        public static bool operator !=(NSByte a, sbyte b) => a.Value != b;
        /// <param name="a"> <see cref="NSByte"/> </param>
        public static NSByte operator --(NSByte a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NSByte"/> </param>
        public static NSByte operator ++(NSByte a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="NSByte"/> </param>
        public static NSByte operator +(NSByte a, NSByte b) => new NSByte(a.Value + b.Value);

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="sbyte"/> </param>
        public static NSByte operator +(NSByte a, sbyte b) => new NSByte(a.Value + b);

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="NSByte"/> </param>
        public static NSByte operator -(NSByte a, NSByte b) => new NSByte(a.Value - b.Value);

        /// <param name="a"> <see cref="NSByte"/> </param>
        /// <param name="b"> <see cref="sbyte"/> </param>
        public static NSByte operator -(NSByte a, sbyte b) => new NSByte(a.Value - b);
    }
}
