// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.InteropServices;

namespace AIO.Security
{
    [Serializable, ComVisible(true)]
    partial struct NSByte
    {
        /// <param name="value"> <see cref="sbyte"/> </param>
        public static implicit operator NSByte(sbyte value) => new NSByte(value);

        /// <param name="value"> <see cref="NSByte"/> </param>
        public static implicit operator sbyte(NSByte value) => value.Value;
    }
}
