// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.InteropServices;

namespace AIO.Security
{
    [Serializable, ComVisible(true)]
    partial struct NShort
    {
        /// <param name="value"> <see cref="short"/> </param>
        public static implicit operator NShort(short value) => new NShort(value);

        /// <param name="value"> <see cref="NShort"/> </param>
        public static implicit operator short(NShort value) => value.Value;
      
        /// <param name="value"> <see cref="byte"/> </param>
        public static implicit operator NShort(byte value) => new NShort(value);
      
        /// <param name="value"> <see cref="sbyte"/> </param>
        public static implicit operator NShort(sbyte value) => new NShort(value);
      
        /// <param name="value"> <see cref="char"/> </param>
        public static implicit operator NShort(char value) => new NShort(value);
      
        /// <param name="value"> <see cref="NByte"/> </param>
        public static implicit operator NShort(NByte value) => new NShort(value);
      
        /// <param name="value"> <see cref="NSByte"/> </param>
        public static implicit operator NShort(NSByte value) => new NShort(value);
      
        /// <param name="value"> <see cref="NChar"/> </param>
        public static implicit operator NShort(NChar value) => new NShort(value);
    }
}
