// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NShort
    { 
        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="NShort"/> </param>
        public static bool operator ==(NShort a, NShort b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="short"/> </param>
        public static bool operator ==(NShort a, short b) => a.Value == b;

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="NShort"/> </param>
        public static bool operator !=(NShort a, NShort b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="short"/> </param>
        public static bool operator !=(NShort a, short b) => a.Value != b;
        /// <param name="a"> <see cref="NShort"/> </param>
        public static NShort operator --(NShort a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NShort"/> </param>
        public static NShort operator ++(NShort a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="NShort"/> </param>
        public static NShort operator +(NShort a, NShort b) => new NShort(a.Value + b.Value);

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="short"/> </param>
        public static NShort operator +(NShort a, short b) => new NShort(a.Value + b);

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="NShort"/> </param>
        public static NShort operator -(NShort a, NShort b) => new NShort(a.Value - b.Value);

        /// <param name="a"> <see cref="NShort"/> </param>
        /// <param name="b"> <see cref="short"/> </param>
        public static NShort operator -(NShort a, short b) => new NShort(a.Value - b);
    }
}
