// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.InteropServices;

namespace AIO.Security
{
    [Serializable, ComVisible(true)]
    partial struct NString
    {
        /// <param name="value"> <see cref="string"/> </param>
        public static implicit operator NString(string value) => new NString(value);

        /// <param name="value"> <see cref="NString"/> </param>
        public static implicit operator string(NString value) => value.Value;
    }
}
