// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NString
    { 
        /// <param name="a"> <see cref="NString"/> </param>
        /// <param name="b"> <see cref="NString"/> </param>
        public static bool operator ==(NString a, NString b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NString"/> </param>
        /// <param name="b"> <see cref="string"/> </param>
        public static bool operator ==(NString a, string b) => a.Value == b;

        /// <param name="a"> <see cref="NString"/> </param>
        /// <param name="b"> <see cref="NString"/> </param>
        public static bool operator !=(NString a, NString b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NString"/> </param>
        /// <param name="b"> <see cref="string"/> </param>
        public static bool operator !=(NString a, string b) => a.Value != b;
    }
}
