// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.InteropServices;

namespace AIO.Security
{
    [Serializable, ComVisible(true)]
    partial struct NUInt
    {
        /// <param name="value"> <see cref="uint"/> </param>
        public static implicit operator NUInt(uint value) => new NUInt(value);

        /// <param name="value"> <see cref="NUInt"/> </param>
        public static implicit operator uint(NUInt value) => value.Value;
      
        /// <param name="value"> <see cref="byte"/> </param>
        public static implicit operator NUInt(byte value) => new NUInt(value);
      
        /// <param name="value"> <see cref="char"/> </param>
        public static implicit operator NUInt(char value) => new NUInt(value);
      
        /// <param name="value"> <see cref="ushort"/> </param>
        public static implicit operator NUInt(ushort value) => new NUInt(value);
      
        /// <param name="value"> <see cref="NByte"/> </param>
        public static implicit operator NUInt(NByte value) => new NUInt(value);
      
        /// <param name="value"> <see cref="NChar"/> </param>
        public static implicit operator NUInt(NChar value) => new NUInt(value);
      
        /// <param name="value"> <see cref="NUShort"/> </param>
        public static implicit operator NUInt(NUShort value) => new NUInt(value);
    }
}
