// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NUInt
    { 
        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="NUInt"/> </param>
        public static bool operator ==(NUInt a, NUInt b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="uint"/> </param>
        public static bool operator ==(NUInt a, uint b) => a.Value == b;

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="NUInt"/> </param>
        public static bool operator !=(NUInt a, NUInt b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="uint"/> </param>
        public static bool operator !=(NUInt a, uint b) => a.Value != b;
        /// <param name="a"> <see cref="NUInt"/> </param>
        public static NUInt operator --(NUInt a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NUInt"/> </param>
        public static NUInt operator ++(NUInt a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="NUInt"/> </param>
        public static NUInt operator +(NUInt a, NUInt b) => new NUInt(a.Value + b.Value);

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="uint"/> </param>
        public static NUInt operator +(NUInt a, uint b) => new NUInt(a.Value + b);

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="NUInt"/> </param>
        public static NUInt operator -(NUInt a, NUInt b) => new NUInt(a.Value - b.Value);

        /// <param name="a"> <see cref="NUInt"/> </param>
        /// <param name="b"> <see cref="uint"/> </param>
        public static NUInt operator -(NUInt a, uint b) => new NUInt(a.Value - b);
    }
}
