// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NULong
    { 
        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="NULong"/> </param>
        public static bool operator ==(NULong a, NULong b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="ulong"/> </param>
        public static bool operator ==(NULong a, ulong b) => a.Value == b;

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="NULong"/> </param>
        public static bool operator !=(NULong a, NULong b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="ulong"/> </param>
        public static bool operator !=(NULong a, ulong b) => a.Value != b;
        /// <param name="a"> <see cref="NULong"/> </param>
        public static NULong operator --(NULong a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NULong"/> </param>
        public static NULong operator ++(NULong a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="NULong"/> </param>
        public static NULong operator +(NULong a, NULong b) => new NULong(a.Value + b.Value);

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="ulong"/> </param>
        public static NULong operator +(NULong a, ulong b) => new NULong(a.Value + b);

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="NULong"/> </param>
        public static NULong operator -(NULong a, NULong b) => new NULong(a.Value - b.Value);

        /// <param name="a"> <see cref="NULong"/> </param>
        /// <param name="b"> <see cref="ulong"/> </param>
        public static NULong operator -(NULong a, ulong b) => new NULong(a.Value - b);
    }
}
