// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;

namespace AIO.Security
{
    partial struct NUShort
    { 
        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="NUShort"/> </param>
        public static bool operator ==(NUShort a, NUShort b) => a.Value == b.Value;

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="ushort"/> </param>
        public static bool operator ==(NUShort a, ushort b) => a.Value == b;

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="NUShort"/> </param>
        public static bool operator !=(NUShort a, NUShort b) => a.Value != b.Value;

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="ushort"/> </param>
        public static bool operator !=(NUShort a, ushort b) => a.Value != b;
        /// <param name="a"> <see cref="NUShort"/> </param>
        public static NUShort operator --(NUShort a)
        {
            a.Value--;
            return a;
        }

        /// <param name="a"> <see cref="NUShort"/> </param>
        public static NUShort operator ++(NUShort a)
        {
            a.Value++;
            return a;
        }

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="NUShort"/> </param>
        public static NUShort operator +(NUShort a, NUShort b) => new NUShort(a.Value + b.Value);

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="ushort"/> </param>
        public static NUShort operator +(NUShort a, ushort b) => new NUShort(a.Value + b);

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="NUShort"/> </param>
        public static NUShort operator -(NUShort a, NUShort b) => new NUShort(a.Value - b.Value);

        /// <param name="a"> <see cref="NUShort"/> </param>
        /// <param name="b"> <see cref="ushort"/> </param>
        public static NUShort operator -(NUShort a, ushort b) => new NUShort(a.Value - b);
    }
}
