// <auto-generated> This code was generated by a tool. </auto-generated>
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Runtime.InteropServices;

namespace AIO.Security
{
    [Serializable, ComVisible(true)]
    partial struct NUShort
    {
        /// <param name="value"> <see cref="ushort"/> </param>
        public static implicit operator NUShort(ushort value) => new NUShort(value);

        /// <param name="value"> <see cref="NUShort"/> </param>
        public static implicit operator ushort(NUShort value) => value.Value;
      
        /// <param name="value"> <see cref="byte"/> </param>
        public static implicit operator NUShort(byte value) => new NUShort(value);
      
        /// <param name="value"> <see cref="char"/> </param>
        public static implicit operator NUShort(char value) => new NUShort(value);
      
        /// <param name="value"> <see cref="NByte"/> </param>
        public static implicit operator NUShort(NByte value) => new NUShort(value);
      
        /// <param name="value"> <see cref="NChar"/> </param>
        public static implicit operator NUShort(NChar value) => new NUShort(value);
    }
}
